title: "Insight Nusantara"
description: "Insight Nusantara - Berita, informasi, dan update terkini dari seluruh dunia"
url: "https://premierbolagg.github.io"
baseurl: "/Insight-Nusantara"  # Jika ada di subfolder

# Plugin
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
